import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from './ApolloProvider';
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ClientProviders from "@/components/ClientProviders";
import { ToastProvider } from '@/context/ToastContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
          <ApolloProvider>
            <CartProvider>
              <ToastProvider>
                <Header />
                <main className="flex-grow">{children}</main>
                <Footer />
                <ClientProviders />
              </ToastProvider>
            </CartProvider>
          </ApolloProvider>
      </body>
    </html>
  );
}

// client logic moved to components/MagicJobWatcher.tsx
